version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"

  php:
    build: ./docker/php
    container_name: php
    ports: ["9000:9000"]
    volumes: ["./symfony/:/var/www/symfony:cached"]

  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports: ["80:80"]
    volumes: ["./symfony/:/var/www/symfony:cached"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
